### PR TITLE
feat: alternative authentication

### LINKED ISSUE #337: Settings configuration for GitHub auth.
The puzzle `285-66616a94` from #285 has to be resolved: 

https://github.com/artipie/artipie/blob/36d95233470090223c491a89f945f48ad1f55b8c/src/main/java/com/artipie/YamlSettings.java#L50-L55

The puzzle was created by @g4s8 on 15-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by dgarus**
Closes #337 

- added an opportunity to set Github auth in YAML settings
- added an opportunity to set a few authentications in YAML settings
```
 credentials:
    -
      type: file
      path: _credentials.yaml
    -
      type: env
```
If there is only one type of credentials, then it can be set up as before
```
 credentials:
      type: file
      path: _credentials.yaml
```
- added tests to check Github auth and alternative authentication

### CODE REVIEW

**Comment by dgarus** [comment]
@g4s8 hi!
Could you please review the PR?

**Comment by dgarus** [comment]
@artipie/maintainers Hello!
 Could anybody do the review, please?

**Review by olenagerasimova — COMMENTED** [review]
@dgarus thanks, code looks good to me. Though, I'd suggest to organize authentications as a yaml list instead of nested maps:
```yaml
credentials:
  - type: env
  - type: github
  - type: file
    path: _credentials.yaml
```
@g4s8 please, take a look. What do you think?

**Comment by dgarus** [comment]
@olenagerasimova @g4s8 
When we use a list, all elements are the same, 
but there is a difference between credentials and authentication (that is only part of credentials), 
so I suggest separating their setup.

**Comment by g4s8** [comment]
I agree with @olenagerasimova - first: nested configuration file looks overcomplicated; second: we may have multiple configurations with the same type, e.g. `[{type: file, path: common.txt}, {type: file, path: private.txt}]`.

Also, @dgarus I didn't get what the problem is
> When we use a list, all elements are the same,
but there is a difference between credentials and authentication (that is only part of credentials)

YAML list items are dynamic, no need to use same structure for each item.

**Comment by dgarus** [comment]
@g4s8 @olenagerasimova 
I see one problem:
What should retun the `com.artipie.YamlSettings#credentials()` when the field `credentials:` is a list of credentials?
Should it be the first element of the list?

**Comment by g4s8** [comment]
> What should retun the `com.artipie.YamlSettings#credentials()` when the field `credentials:` is a list of credentials? Should it be the first element of the list?

@dgarus it could be an ordered list or some object which encapsulates this list and can authenticate request using this list. In you example you are using almost the same approach:
```
credentials:
    type: env
    alternative_auth:
      - type: github
      - type: file
        path: _credentials.yaml
```
So the implementation could be very similar. But I don't understand why one credential's source should be a part of another (semantically).

**Comment by dgarus** [comment]
@olenagerasimova @g4s8 
Hello!
I fixed the YAML configuration of credentials.
Please, have a look.

**Review by g4s8 — APPROVED** [review]
@dgarus thanks!

**Comment by baudoliver7** [comment]
@g4s8 Please, could you set `pdd-lint` to `required` ? If you check [details](https://github.com/artipie/artipie/runs/5067182107?check_suite_focus=true), you will see that `pdd` fail because of a short description.

**Pull request merged**
