### PR TITLE
fix: github auth is broken

### PR DESCRIPTION
**Pull request by olenagerasimova**
I've caught the following exception on Central:
```
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
	at com.artipie.settings.cache.CachedUsers.lambda$user$0(CachedUsers.java:64)
	at com.artipie.asto.misc.UncheckedScalar.value(UncheckedScalar.java:34)
	at com.artipie.settings.cache.CachedUsers.user(CachedUsers.java:65)
	at com.artipie.settings.YamlSettings$Cached.user(YamlSettings.java:322)
	at com.artipie.http.auth.Authentication$Joined.lambda$user$0(Authentication.java:224)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.artipie.http.auth.Authentication$Joined.user(Authentication.java:226)
	at com.artipie.auth.LoggingAuth.user(LoggingAuth.java:49)
	at com.artipie.http.auth.BasicAuthScheme.lambda$user$3(BasicAuthScheme.java:59)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.artipie.http.auth.BasicAuthScheme.user(BasicAuthScheme.java:59)
	at com.artipie.http.auth.BasicAuthScheme.authenticate(BasicAuthScheme.java:44)
	at com.artipie.http.auth.AuthSlice.response(AuthSlice.java:65)
	at com.artipie.http.Slice$Wrap.response(Slice.java:62)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:53)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:69)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:72)
	at com.artipie.http.Slice$Wrap.response(Slice.java:62)
	at com.artipie.http.slice.TrimPathSlice.response(TrimPathSlice.java:95)
	at com.artipie.http.ContinueSlice.response(ContinueSlice.java:45)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:44)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at com.jcabi.http.request.DefaultResponse.as(DefaultResponse.java:161)
	at com.jcabi.github.RtJson.fetch(RtJson.java:76)
	at com.jcabi.github.RtUser.json(RtUser.java:166)
	at com.jcabi.github.RtUser.login(RtUser.java:121)
	at com.artipie.auth.GithubAuth.lambda$new$0(GithubAuth.java:47)
	at com.artipie.auth.GithubAuth.user(GithubAuth.java:69)
	at com.artipie.settings.cache.CachedUsers$Data.user(CachedUsers.java:137)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 46 more
Caused by: java.lang.ClassNotFoundException: org.hamcrest.Matcher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 62 more
```
From stack trace, it's clear that `jcabi-github` uses `hamcrest` in the main code and it's not correct to exclude the library. 
Also, I've updated asto. As s3 is now in a separate module, I've removed tests related to s3.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@dgarus @ChGen please, take a look, I need this PR merged to finalize Python article, so we can send it for review

**Comment by ChGen** [comment]
@olenagerasimova , why removing some tests was still necessary?

**Comment by olenagerasimova** [comment]
> @olenagerasimova , why removing some tests was still necessary?

@ChGen because s3 storage is now not a part of asto-core, it was moved to separate module and `jar` and thus can not be instantiated from artipie directly. Artipie is not supposed to depend on all the possible storage implementations, s3, for example; the implementations should be added by users as jars when required.

**Comment by ChGen** [comment]
@olenagerasimova , thanks!

**Review by ChGen — APPROVED** [review]

**Pull request merged**
