### PR TITLE
Don't release .jar to GitHub, since we release it to maven central now.

### PR DESCRIPTION
**Pull request by ChGen**
Don't release .jar to GitHub, since we release it to maven central now.
Part of #1206

### CODE REVIEW

**Comment by ChGen** [comment]
@olenagerasimova , please review.

**Review by olenagerasimova — DISMISSED** [review]
thanks, what about wiki? Do not correct it from github, do it from the repository via PR

**Comment by ChGen** [comment]
@olenagerasimova , I've updated URL in the Wiki, please review.

**Review by olenagerasimova — APPROVED** [review]
@ChGen thanks, merging

**Pull request merged**
