### PR TITLE
Examples scripts

### PR DESCRIPTION
**Pull request by g4s8**
#847 - added common bash utils for all examples, refactored npm to use it, added `trap` to stop artipie container in any case

### CODE REVIEW

**Review by olenagerasimova — APPROVED** [review]
@g4s8 thanks, looks good. But, personally, I'd prefer the way the scripts were - when entire step by step process is duplicated in each example. It's simpler to read and faster to understand single file script than several files script.

**Comment by g4s8** [comment]
> @g4s8 thanks, looks good. But, personally, I'd prefer the way the scripts were - when entire step by step process is duplicated in each example. It's simpler to read and faster to understand single file script than several files script.

@olenagerasimova there were a bug in a script related to docker lifecycle: if the script fails in the middle the docker container will never be stopped. So now we have to fix this bug in each script, this is why I created a function to start docker and automatically stop it on script finish or error. If we'll have a bug or improvement in future for docker starting, we'll change only base script, and not each of the examples.

**Comment by olenagerasimova** [comment]
@g4s8 sure the way you suggested is easier to fix and maintain, no arguments here. I've expressed my opinion from external user point of view, but I guess it's the matter of taste.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#848` is not assigned, can't get performer

**Pull request merged**
