### PR TITLE
Added NPM adapter

### PR DESCRIPTION
**Pull request by g4s8**
#47 - integrated NPM adapter as Artipie module

### CODE REVIEW

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#48` is not assigned, can't get performer

**Comment by 0crat** [comment]
This pull request [#48](https://github.com/artipie/artipie/issues/48) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3f12d19a-b48d-467c-b0db-8ab752c10ef9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/artipie/issues/48#issuecomment-603437404))

@Vatavuk This is what I know about this job in [CT2E6TK9B](https://www.0crat.com/p/CT2E6TK9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#48](https://github.com/artipie/artipie/issues/48) is [in scope](http://www.zerocracy.com/policy.html#14) for 1days
  * The role is `REV`
  * The job is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @vatavuk[/z](https://www.0crat.com/u/vatavuk) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%2348%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by Vatavuk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/artipie/issues/48#issuecomment-604105212))

@Vatavuk This is what I know about this job in [CT2E6TK9B](https://www.0crat.com/p/CT2E6TK9B), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#48](https://github.com/artipie/artipie/issues/48) is [in scope](http://www.zerocracy.com/policy.html#14) for 3days
  * The role is `REV`
  * The job is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @vatavuk[/z](https://www.0crat.com/u/vatavuk) will get 25% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fartipie%2348%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/48#issuecomment-604233382))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#48](https://github.com/artipie/artipie/issues/48), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#48](https://github.com/artipie/artipie/issues/48) is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/fbb3b9e1-f1d2-438f-885e-b41d5109f886); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/48#issuecomment-604364563))

@g4s8 There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 11@a8b1883598e0, thread: PQ-CT2E6TK9B
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:artipie/artipie#48] declared for identity constraint of element "speed".
```

[0.52](https://github.com/zerocracy/farm): CID: [de351d2a-03c7-4060-ac01-b1518728e10f](https://www.0crat.com/footprint/CT2E6TK9B/de351d2a-03c7-4060-ac01-b1518728e10f), Type: "Order was finished"

**Comment by 0crat** [comment]
Job audit: performer @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)[/z](https://www.0crat.com/u/amihaiemil) didn't make CR comments

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/48#issuecomment-604364536))

@g4s8 The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#48](https://github.com/artipie/artipie/issues/48), please stop working. Reason for job resignation: Order was cancelled

**Pull request merged**
