### PR TITLE
#663 - Add timeout

### LINKED ISSUE #663: Add timeout in NugetITCase
In some case `NugetITCase` hangs indefinitely  in `maven-build (ubuntu-latest, 11)` or `maven-build (ubuntu-latest, 13)`. Let's add `@Timeout()` for method `shouldPushPackage()` for quick notification of failure.

### PR DESCRIPTION
**Pull request by genryxy**
Closes #663 
Add `@Timeout()` for method `shouldPushPackage()`

### CODE REVIEW

**Comment by 0crat** [comment]
@genryxy[/z](https://www.0crat.com/u/genryxy) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, this fix helps. But the test will be still "flaky" and fail when nothing is broken. Have you tried to investigate why it hangs up? Does it happen with other tests as well?

**Comment by genryxy** [comment]
@olegmoz it doesn't happen with other tests. I tried to investigate why it hangs up, but didn't succeed. It looks strange that any `--api-key` could be passed and it will work. 
Maybe it's better to disable this test because it sometimes doesn't work properly?

**Review by olegmoz — APPROVED** [review]
@genryxy okey, lets try and see how it goes with timeout. If it will fail too often then investigate further or disable it

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#664` is not assigned, can't get performer

**Pull request merged**
