### PR TITLE
Debian delete artifacts

### PR DESCRIPTION
**Pull request by Tzahifer**
delete debian artifacts from repository

### CODE REVIEW

**Comment by Tzahifer** [comment]
@dgarus @ChGen can you please review it?

**Comment by ChGen** [comment]
@Tzahifer , please, check GitHub logs. Looks like some tests are failing.

**Comment by Tzahifer** [comment]
@ChGen can you please help with this?
the errors don't seem to be related to the changes i made

**Comment by ChGen** [comment]
@Tzahifer , I'll try took look into this deeper, but a bit later. Probably next week.

**Comment by ChGen** [comment]
@Tzahifer , please rebase via fresh origin/master, so we could recheck it.

**Comment by Tzahifer** [comment]
@ChGen i merged with master, can you run the check manually?
i tried to update the GHA but it's not running

**Review by ChGen — APPROVED** [review]
LGTM

**Pull request merged**
