### PR TITLE
Fix docker and pypi proofs

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #459.

### CODE REVIEW

**Comment by Sammers21** [comment]
@olegmoz, the docker proof has been fixed by this PR. Can we merge?

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 updated pypi-adapter has been released already, please update it's version as well and we are good to merge

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#473` is not assigned, can't get performer

**Pull request merged**
