### PR TITLE
Files proxy IT with `TestDeployment`

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #855 
Remade `FileProxyAuthIT` to use `TestDeployment`, moved and renamed `BinaryITCase`, moved resources to separate directory.

### CODE REVIEW

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova maybe we can place all integration tests in one package? since it's actually not running against some specific class or package but against Artipie server

**Comment by olenagerasimova** [comment]
@g4s8 we could, but I'm not sure if it will be convenient: there are several test classes for each adapter, so the common package will have a lot of classes, and corresponding package in test resources with repository settings also will very huge.

**Comment by g4s8** [comment]
> @g4s8 we could, but I'm not sure if it will be convenient: there are several test classes for each adapter, so the common package will have a lot of classes, and corresponding package in test resources with repository settings also will very huge.

@olenagerasimova but in that case it'll be not clear where to find integration test class for adapters, e.g. we don't have package `com.artipie.rpm` in `com.artipie:artipie` module, and the test is not exactly is running against `rpm` package but for Artipie web service with rpm module enabled

**Comment by olenagerasimova** [comment]
@g4s8 hm, it's clear enough from my point of view. If we want it transparent, than package with these tests should be called `adapters integration tests`

**Review by g4s8 — APPROVED** [review]
@olenagerasimova ok, let's keep it here

**Pull request merged**
