### PR TITLE
97 java version

### PR DESCRIPTION
**Pull request by artemlazarev**
add java 13 to maven build target

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#107](https://github.com/artipie/artipie/issues/107) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b328cf41-36ee-4fe3-a630-06728c3b5f49); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@g4s8 please remove this issue from the scope

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/107#issuecomment-621293767))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#107](https://github.com/artipie/artipie/issues/107), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/107#issuecomment-621293800))

@g4s8 Job `gh:artipie/artipie#107` is not assigned, can't get performer

**Pull request merged**
