### PR TITLE
#835 - Auth test

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #835 
Added debian test with auth

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, looks good to merge

**Comment by olegmoz** [comment]
@olenagerasimova tests are failing, please fix

**Comment by olenagerasimova** [comment]
@olegmoz tests are ok, seems like it was some glitch

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#838` is not assigned, can't get performer

**Pull request merged**
