### PR TITLE
#843 - update adapters

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated several adapters.

### CODE REVIEW

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@olenagerasimova please check build failures:
> Error:  /home/runner/work/artipie/artipie/src/main/java/com/artipie/SliceFromConfig.java:[213,94] incompatible types: com.artipie.asto.Storage cannot be converted to com.artipie.composer.Repository

**Comment by olenagerasimova** [comment]
@g4s8 thanks, corrected

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Comment by olenagerasimova** [comment]
@g4s8 please merge and release Artipie, all checks passed

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#845` is not assigned, can't get performer

**Pull request merged**
