### PR TITLE
#116 - add pypi-adapter support to main project

### PR DESCRIPTION
**Pull request by artemlazarev**
Added pypi-adapter to main artipie project. Closes 
https://github.com/artipie/artipie/issues/116 ticket.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#133](https://github.com/artipie/artipie/issues/133) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/b4e3fbee-042c-4a8d-bbfa-0ca26c55e91d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by carlosmiranda** [comment]
@artemlazarev this looks good. Just one thing, please edit your pull request description to add a link back to the original ticket. See [policy](http://www.zerocracy.com/policy.html#42).

> Pull request description explains the solution proposed and contains a link to the original ticket it is related to

**Comment by artemlazarev** [comment]
@carlosmiranda  description updated

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@carlosmiranda please make sure you will find at least 3 issues during next CR, thanks

**Comment by carlosmiranda** [comment]
@sereshqua agreed, thanks

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable  ([here](https://github.com/artipie/artipie/issues/133#issuecomment-628030971))

@sereshqua The project doesn't have enough funds, can't make a payment

**Pull request merged**
