### PR TITLE
#607 - Verify upload chart

### PR DESCRIPTION
**Pull request by genryxy**
Part of #607 
Verify uploading with authentication in `helmITCase`

### CODE REVIEW

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy I think that integration tests should operate on `helm` command instead of testing HTTP endpoints, something similar to what is done here: https://github.com/artipie/helm-adapter/blob/master/src/test/java/com/artipie/helm/HelmCompatibilityITCase.java

**Comment by genryxy** [comment]
@olegmoz thanks, corrected

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#749` is not assigned, can't get performer

**Pull request merged**
