### PR TITLE
Added integration test for binary repository

### PR DESCRIPTION
**Pull request by g4s8**
For #855 - added tests for upload and download for binary repository,
introduced new methods for working with `TestDeployment`,
fixed users and groups in Dockerfile for AccessDeniedException on write
in container.

### CODE REVIEW

**Review by olenagerasimova — APPROVED** [review]
@g4s8 thanks, looks good to me

**Comment by 0crat** [comment]
Job [#871](https://github.com/artipie/artipie/issues/871) is closed, can't start order

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova)[/z](https://www.0crat.com/u/olenagerasimova) didn't make CR comments

**Pull request merged**
