### PR TITLE
feat: added skeletons for repo configs operations

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #1099 
Added interfaces for repository settings Rest API operations: to manage repos and repo permissions settings. 
Also, removed unused and not required any more classes, moved some classes from/to `repo` package.

### CODE REVIEW

**Review by dgarus — CHANGES_REQUESTED** [review]
@olenagerasimova thanks!
Take a look please on my comments.

**Comment by olenagerasimova** [comment]
@dgarus thanks
I've renamed interfaces and added DTO interfaces (I think they better be interfaces so we can make various implementations in the future and use them as for read as for write purposes).

**Comment by olenagerasimova** [comment]
@dgarus please, take a look

**Review by dgarus — APPROVED** [review]
@olenagerasimova thanks!

**Pull request merged**
