### PR TITLE
Fixed new server autoconfiguration, updated README

### LINKED ISSUE #864: java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml
1. Create /var/artipie/ directory
2. Run `docker run -d --name artipie -v /var/artipie:/var/artipie -p 8080:80  -e ARTIPIE_USER_NAME=artipie -e ARTIPIE_USER_PASS=qwerty artipie/artipie:latest`
3. After few seconds run:
```
docker logs artipie
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at com.artipie.JavaResource.copy(JavaResource.java:80)
	at com.artipie.VertxMain.settings(VertxMain.java:165)
	at com.artipie.VertxMain.start(VertxMain.java:106)
	at com.artipie.VertxMain.main(VertxMain.java:152)
```

### PR DESCRIPTION
**Pull request by g4s8**
Fixes #864 - fixed standard resources copying on first start of
empty server, updated documentation.

### CODE REVIEW

**Comment by genryxy** [comment]
@g4s8 there are a few qulice violations. Please fix them

**Comment by g4s8** [comment]
@genryxy fixed

**Review by genryxy — APPROVED** [review]
@g4s8 thanks, looks good to me

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#865` is not assigned, can't get performer

**Pull request merged**
