### PR TITLE
#804 - handle exception on repo config parsing

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #804 
Handle exception when parsing repo config on start

### CODE REVIEW

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, I'd suggest to add a test for this issue

**Comment by olenagerasimova** [comment]
@olegmoz added test

**Comment by olenagerasimova** [comment]
@olegmoz I've renamed the test as we descussed

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Comment by olegmoz** [comment]
@rultor release, tag=`0.13.1`

**Pull request merged**
