### PR TITLE
Dont run test on docker image build

### LINKED ISSUE #466: Proofs should not run tests
Building Artipie in proofs involves running all the tests and other verification. That makes these workflows run longer and be more prone to errors, issue #465 is an example

### PR DESCRIPTION
**Pull request by Sammers21**
Tests are ignored during the image build

Closes #466.

### CODE REVIEW

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by Sammers21** [comment]
@olegmoz, review the Pull Request, please.

**Review by olegmoz — APPROVED** [review]
@Sammers21 nice, thank you

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#469` is not assigned, can't get performer

**Pull request merged**
