### PR TITLE
#169 - added test and fixed RpPermissionsTest

### PR DESCRIPTION
**Pull request by olenagerasimova**
Added test to reproduce #169 and found out:
- bug in eo-yaml: asterisk in sequence escaped with `\` is not read correctly, https://github.com/decorators-squad/eo-yaml/issues/380
-  `RpPermissionsTest` was false positive because of the strange ctor (test always positive whatever `Proc` you pass)
```
public MatcherOf(final Proc<T> proc) {
    this(new FuncOf<>(proc, true));
}
```

Also, I've updated `http`. 

@g4s8 please, could you review the tests and explain what situation am I missing here? Now it seems that everything works as we want.

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/artipie/artipie/issues/266#issuecomment-654673409))

@olenagerasimova This pull request [#266](https://github.com/artipie/artipie/issues/266) is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0b9b2543-b529-4c62-8dee-ef43defe7e14); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 please do not merge yet, I have some corrections to make

**Comment by olenagerasimova** [comment]
@g4s8 shame on me: I've read docs about yaml not carefully enough, sorry. Backslash in not an escape character, quotation marks (both double and singe) are. I've fixed all examples and readme.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: performer @g4s8[/z](https://www.0crat.com/u/g4s8)[/z](https://www.0crat.com/u/g4s8) didn't make CR comments

**Pull request merged**
