### PR TITLE
97-java-versions

### PR DESCRIPTION
**Pull request by artemlazarev**
closes - https://github.com/artipie/artipie/issues/97 . Add matrix with java 11 and 13 to maven build process.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#105](https://github.com/artipie/artipie/issues/105) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/6fac51fd-508a-4809-8149-9ff8c05587d0); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@artemlazarev it seems you forgot to rebase on fresh master branch. Can you please checkout from upstream master?

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/105#issuecomment-620095502))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#105](https://github.com/artipie/artipie/issues/105), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/105#issuecomment-620096656))

@g4s8 Job `gh:artipie/artipie#105` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/105#issuecomment-620096656))

@g4s8 Pull request [#105](https://github.com/artipie/artipie/issues/105) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#105` is not assigned, can't get performer

**Pull request closed without merging**
