### PR TITLE
feat: generate auth token

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #1099 
Added endpoint to obtain jwt token. Tokens are generated using the [symmetric keys](https://vertx.io/docs/vertx-auth-jwt/java/#_using_symmetric_keys) and we need to figure out where and how to store secret word (for now it's just hard-coded).

### CODE REVIEW

**Review by dgarus — APPROVED** [review]
@olenagerasimova thanks!

**Comment by olenagerasimova** [comment]
@dgarus let's change lambda variables names and yamls?

**Comment by dgarus** [comment]
> @dgarus let's change lambda variables names and yamls?

ok, I don't mind

**Comment by olenagerasimova** [comment]
@dgarus corrected and it seems we do not have to suppress anything as qulice is not complaining to camel case in lambdas.

**Review by dgarus — APPROVED** [review]
@olenagerasimova thanks, look good for me.

**Review by andpopov — APPROVED** [review]
@olenagerasimova thanks!

**Pull request merged**
