### PR TITLE
#332 - Docker virtual repository support

### LINKED ISSUE #332: Support for writes to `docker-proxy` repository
If there is storage configured for Docker proxy repository, then it should be possible to do write operations to such repository as well making such repository `virtual`.

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #332 
Using storage configured in proxy for write operations

### CODE REVIEW

**Comment by olegmoz** [comment]
@g4s8 pdd-lint is failing on parsing a binary file in `examples` folder, isn't pdd lint required for merge of PR?

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by Vatavuk** [comment]
@0crat refuse

**Pull request merged**
