### PR TITLE
#572 - read/write groups in Users.FromStorageYaml

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #572 
Renamed `Credenctials` to `Users` which seem much more appropriate and implemented read/write user groups operation.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, it all looks good. Though in name of PR you state that write is implemented, but as I see only reading groups from YAML was added in production code or am I wrong?

**Comment by olenagerasimova** [comment]
@olegmoz user groups are added to `credenctial.yaml` in `Users.FromStorageYaml#add`, lines 186-192

**Comment by olegmoz** [comment]
@olenagerasimova oh, that's right, thanks

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#617` is not assigned, can't get performer

**Pull request merged**
