### PR TITLE
feat: corrected readme and Dockerfile

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #1099

- corrected quickstart section of readme
- removed not needed files
- corrected static resource link to relative ([it's not corrected to obtain resources uri](https://stackoverflow.com/questions/20389255/reading-a-resource-file-from-within-jar))

Please, when verifying quickstart do not forget to build Docker image from this branch and use `1.0-SNAPSHOT` version.

### CODE REVIEW

**Review by dgarus — CHANGES_REQUESTED** [review]
@olenagerasimova thanks!

**Comment by olenagerasimova** [comment]
@dgarus thanks, corrected as we discussed

**Review by dgarus — APPROVED** [review]
Thanks! LGTM

**Comment by olenagerasimova** [comment]
@dgarus please, approve once again, I've change default Rest API port to avoid conflicts with ITs

**Review by dgarus — APPROVED** [review]

**Pull request merged**
