### PR TITLE
Fixed CI build

### PR DESCRIPTION
**Pull request by g4s8**
Fixed CI trigger action

### CODE REVIEW

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by Sammers21** [comment]
This pull request has no diff:
image

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#21` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
