### PR TITLE
Docker profile

### PR DESCRIPTION
**Pull request by g4s8**
#851 - building Docker with dependency cache: using Maven profile to build Docker image with separate image layers for dependencies and target small jar.

### CODE REVIEW

**Comment by genryxy** [comment]
@g4s8 probably to add `@todo` to enable disabled docker test `DockerLocalIT#shouldPullPushed`, DockerLocalAuthIT#shouldPullPushed`, ` DockerOnPortIT#shouldPullPushed`?

**Comment by g4s8** [comment]
> @g4s8 probably to add `@todo` to enable disabled docker test `DockerLocalIT#shouldPullPushed`, `DockerLocalAuthIT#shouldPullPushed`, ` DockerOnPortIT#shouldPullPushed`?

@genryxy sure, I'll add a todo, when I'm sure what tests are not working on the CI

**Comment by g4s8** [comment]
@genryxy done. Also, I've explained the testing process in this wiki page: https://github.com/artipie/artipie/wiki/Testing please let me know if you have any objectsion or questions

**Review by genryxy — APPROVED** [review]
@g4s8 thanks. To tell the truth, I can't carefully look at this PR, because unfortunately I'm quite poorly experienced in this topic. As I understood, the main idea is that we create docker container, install required environment and after that check script for a specific repository was successfully executed. 
By the way, it becomes a little bit more difficult to understand what proof is failed.

**Comment by genryxy** [comment]
@g4s8 in this PR `proof` github action appeared. It always has status `Expected — Waiting for status to be reported`

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#852` is not assigned, can't get performer

**Pull request merged**
