### PR TITLE
#15 - Migrated to com.artipie parent pom & fixed URLs in pom.xml

### PR DESCRIPTION
**Pull request by olegmoz**

### CODE REVIEW

**Comment by olegmoz** [comment]
@g4s8 please review

**Comment by g4s8** [comment]
@olegmoz I'd wait #18 PR to be merged, since there will be conflict in dependencies

**Comment by 0crat** [comment]
This pull request [#16](https://github.com/artipie/artipie/issues/16) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/2bf18d29-1425-43ed-93c3-22450d735f1d); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by olegmoz** [comment]
@yegor256 please review

**Comment by iakunin** [comment]
@olegmoz just only one advice: it'd better to decide with @g4s8 which PR will be merged in the first place (this or https://github.com/artipie/artipie/pull/18).

**Comment by 0crat** [comment]
Job was finished in 38 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Pull request merged**
