### PR TITLE
Test for `/api/security/users/{{name}}`

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #965 
Added test for `/api/security/users/{{name}}` endpoint

### CODE REVIEW

**Comment by olenagerasimova** [comment]
@g4s8 I'm afraid I need your help here. Please, check the added test: it's supposed to return bad request, but it's failing with "thread is blocked" exception. I cannot understand where and what is blocked, all the tests in management-api works fine.

Note that because of the problem in containers with access to files (it's described at the beginning of the class in todo), we cannot alter repos, credentials and other settings files, that's why I added negative (that returns bad request) test.

**Comment by g4s8** [comment]
> @g4s8 I'm afraid I need your help here. Please, check the added test: it's supposed to return bad request, but it's failing with "thread is blocked" exception. I cannot understand where and what is blocked, all the tests in management-api works fine.
> 
> Note that because of the problem in containers with access to files (it's described at the beginning of the class in todo), we cannot alter repos, credentials and other settings files, that's why I added negative (that returns bad request) test.

@olenagerasimova please check logs before "thread is blocked" exception, usually it's caused by another unhandled exception in runtime.

**Comment by olenagerasimova** [comment]
@g4s8 here is the stack trace 
```
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: WARNING: Thread Thread[vert.x-eventloop-thread-1,5,main]=Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5178 ms, time limit is 2000 ms
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: io.vertx.core.VertxException: Thread blocked
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:42)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Flowable.subscribe(Flowable.java:14918)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3603)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3603)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3603)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3603)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3603)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.subscribe(Single.java:3589)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//hu.akarnokd.rxjava2.interop.SingleInterop.lambda$get$0(SingleInterop.java:49)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//hu.akarnokd.rxjava2.interop.SingleInterop$$Lambda$144/0x0000000800d3efd8.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.reactivex.Single.to(Single.java:3872)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.management.api.artifactory.AddUpdateUserSlice.info(AddUpdateUserSlice.java:107)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.management.api.artifactory.AddUpdateUserSlice.lambda$response$3(AddUpdateUserSlice.java:58)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.management.api.artifactory.AddUpdateUserSlice$$Lambda$320/0x0000000800e941e0.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.Optional.map(Optional.java:260)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.management.api.artifactory.AddUpdateUserSlice.response(AddUpdateUserSlice.java:56)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.RtRulePath.response(RtRulePath.java:53)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:69)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute$$Lambda$270/0x0000000800e872a8.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.eval
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: uate(AbstractPipeline.java:234)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute.response(SliceRoute.java:72)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.auth.AuthSlice.lambda$null$0(AuthSlice.java:70)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.auth.AuthSlice$$Lambda$319/0x0000000800e93d88.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.Optional.map(Optional.java:260)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.auth.AuthSlice.lambda$response$2(AuthSlice.java:66)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.auth.AuthSlice$$Lambda$309/0x0000000800e91fb0.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.auth.AuthSlice.response(AuthSlice.java:65)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.Slice$Wrap.response(Slice.java:62)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:44)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice$$Lambda$275/0x0000000800e8c450.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice.response(AsyncSlice.java:44)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.management.api.ApiAuthSlice.response(ApiAuthSlice.java:97)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:44)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice$$Lambda$275/0x0000000800e8c450.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:144)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.async.AsyncSlice.response(AsyncSlice.java:44)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.Slice$Wrap.response(Slice.java:62)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.RtRulePath.response(RtRulePath.java:53)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:69)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute$$Lambda$270/0x0000000800e872a8.apply(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.rt.SliceRoute.response(SliceRoute.java:72)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.Slice$Wrap.response(Slice.java:62)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:71)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.slice.LoggingSlice$$Lambda$268/0x0000000800e86c00.send(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:79)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:58)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.ResponseMetricsSlice$$Lambda$267/0x0000000800e85c28.send(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:83)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//com.artipie.vertx.VertxSliceServer$$Lambda$199/0x0000000800db44c8.handle(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.net.impl.VertxHandler$$Lambda$253/0x0000000800e3cd60.handle(Unknown Source)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerCo
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: ntext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR: 	at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)
[INFO] docker-java-stream-1349737394 com.artipie.test.TestDeployment$ArtipieContainer: [artipie] STDERR:
```

**Comment by g4s8** [comment]
@olenagerasimova I think we can implement it in artipie/front

**Comment by olenagerasimova** [comment]
@g4s8 yes, I agree, let's close this PR

**Pull request closed without merging**
