### PR TITLE
let main thread exit after initialization

### LINKED ISSUE #151: Artipie start message is not displayed
image

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #151

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#152](https://github.com/artipie/artipie/issues/152) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d93c05e6-954c-4019-98b8-5b871eb149bd); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/152#issuecomment-633587045))

@g4s8 Job `gh:artipie/artipie#152` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat pay 15min @paulodamaso

**Pull request merged**
