### PR TITLE
Disable debug logs for tests

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #634.

### CODE REVIEW

**Comment by olegmoz** [comment]
@Sammers21 do not think that it's good idea to disable all DEBUG output. It may be useful to understand  what went wrong. I see that most of spam comes from `MeasuredStorage` and tried to handle it, see https://github.com/artipie/artipie/pull/638

**Comment by olegmoz** [comment]
@Sammers21 the issue has already been handled, see merged PR https://github.com/artipie/artipie/pull/638

**Comment by Sammers21** [comment]
@olegmoz, я не очень рад это слышать

**Comment by Sammers21** [comment]
@olegmoz, то есть сразу после того как я отрыл тикет, сделал этот пул реквест. Ты сделал еще один такой же тикет отправил свой пул реквест, смержил и нормально, да?

**Comment by Sammers21** [comment]
Безобразие

**Comment by olegmoz** [comment]
@Sammers21 sorry, but I did not see your issue before submitting another issue and the PR. But it seems that solution to the problem we came up with was very different anyway. Then again, I am very sorry you have wasted your time on solving this issue. To avoid that kind of problem in future you may coordinate with other team members before taking on some issue

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#636` is not assigned, can't get performer

**Comment by 0crat** [comment]
Pull request [#636](https://github.com/artipie/artipie/issues/636) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
