### PR TITLE
Cosmetic corrections in readme

### PR DESCRIPTION
**Pull request by olenagerasimova**
Made several corrections in readme.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#67](https://github.com/artipie/artipie/issues/67) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/9e5e83d8-e7ff-462f-be31-125a4a52b5b9); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/67#issuecomment-611092688))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#67](https://github.com/artipie/artipie/issues/67), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#67](https://github.com/artipie/artipie/issues/67) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0abd6074-d12b-45fc-9d45-03105604d712); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/67#issuecomment-611436112))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#67](https://github.com/artipie/artipie/issues/67), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#67` is not assigned, can't get performer

**Pull request merged**
