### PR TITLE
#574 - permissions mapping in AddUpdatePermissionSlice

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #574 
I've added permissions mapping to `AddUpdatePermissionSlice` before saving them to repo config, possible permissions values are from [this](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json) docs.
Note that
- `annotate`, `managedXrayMeta` and `distribute` are not included as we do not know what they mean and how to translate them
- `admin` and `manage` are translated to `*` which means any actions will be allowed to these users

I'm planning to document it when we discuss, possibly change something and merge this PR.

### CODE REVIEW

**Comment by olegmoz** [comment]
@olenagerasimova I am not sure at this point that we need this translation when actions added in https://github.com/artipie/http/pull/239

Permissions may be stored as-is and translated when permission is checked. Saving permissions as-is will also allow to return expected values in `GET` requests.

**Comment by olenagerasimova** [comment]
@olegmoz hm, as these are artifactory-like terms and permissions, I'd not want them to penetrate dipper than this API layer. 
I consider the whole permission-translation task consist of two parts:
1. Unify our internal terms (actions from https://github.com/artipie/http/pull/239 allow us to achieve this goal), actions names contains terms from our adapters only
2. Translate artifactory-like terms to artipie terms and back, this PR serves this goal partly

What do you say?

**Comment by olegmoz** [comment]
@olenagerasimova I also would rather avoid passing Artifactory API logic beyond the slices, but I am not sure how permissions translated into `*` will work. First we receive request to grant permission `admin` to some user, we store `*` instead. How will translate `*` back to `admin` later? How will we know that it is `admin` permission and not `manage`? Can't think of a solution, do you have some solution in mind?

And for `r`, `read, `w`, `write` and others we have translations in `Action.ByString` already, so no need to do it here

**Comment by olenagerasimova** [comment]
@olegmoz I understand that we will not be able to return exact excepted values, but is it really required? 
As for `*` I was thinking to translate it into `manage` as artifactory "PermissionTargetV2+json" does not have "admin".

If we are not going to merge it, then we should extend `Actions.Standard` with `admin` or `manage` value and probably add some values to existing items...

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, got it. As the translation is not ambiguous the solution is nice. And we won't have external permission names deep in our code

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#593` is not assigned, can't get performer

**Pull request merged**
