### PR TITLE
Ci checks

### PR DESCRIPTION
**Pull request by g4s8**
#120 - more CI checks, reorganized the structure

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#177](https://github.com/artipie/artipie/issues/177) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/5e27629b-cf5f-46ad-aa2d-e23d2fe4e776); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@0crat out

**Comment by g4s8** [comment]
@paulodamaso refusing - it's just a reorganization of config file

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/177#issuecomment-635227457))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#177](https://github.com/artipie/artipie/issues/177), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/artipie/artipie/issues/177#issuecomment-635227480))

@g4s8 Job `gh:artipie/artipie#177` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#177` is not assigned, can't get performer

**Pull request merged**
