### PR TITLE
feat: update `eo-yaml`

### LINKED ISSUE #1198: Yaml sequence formatting
Currently used `eo-yaml` requires not convenient formatting of yaml sequence:
```yaml
some_sequence:
  -
    key1: value1
    key2: value2
  -
    key3: velue3
```
when sequence items are placed differently (without line break after `-`), the sequence is parsed incorrectly.

Let's use another yaml reader or update `eo-yaml`.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #1198

Updated eo-yaml to support normal formatting of the yaml sequences with mapping items. New version seem to work much better with sequences and overall. I'll explain all the corrections further, use [validator](https://www.yamllint.com/) to confirm:
1. SSL tests: space is required between `:` and yaml mapping value
2. `DockerProxyTest`: actually, the test was working incorrectly because of the error with parsing sequences in eo-yaml
3. `YamlPermissions`: current eo-yaml version requires escaping `*` sign with quotation marks or `\` when obtaining sequence, I've added quotation marks and `\` and corresponding matchers and data into test. Also, note, that `*` sign HAVE to be put into quotation marks or used with `\`, otherwise the yaml is not valid.
4. `AuthAndPermissionsTest` was corrected to use files and thus to avoid any possible confusions

### CODE REVIEW

**Review by dgarus — APPROVED** [review]
@olenagerasimova thanks!
LGTM

**Comment by olenagerasimova** [comment]
@dgarus not ready yet, please, do not merge!

**Comment by dgarus** [comment]
> @dgarus not ready yet, please, do not merge!

ok

**Comment by olenagerasimova** [comment]
@dgarus now it's ready, please, review

**Review by dgarus — APPROVED** [review]

**Pull request merged**
