### PR TITLE
For #46: Added version parameter to dockerfile

### PR DESCRIPTION
**Pull request by paulodamaso**
For #46 
- Added version parameter to dockerfile
- Uses version parameter to version maven artifact

### CODE REVIEW

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@paulodamaso we also need to use this tag argument in docker build action: https://github.com/artipie/artipie/blob/master/.github/workflows/docker-release.yml

**Comment by g4s8** [comment]
@paulodamaso we're waiting few urgent fixed from #52 and #53, this is why I'm not merging this PR (it may conflict with new fixed with high priority)

**Comment by paulodamaso** [comment]
@g4s8 May I continue to work on this then? I can put it on hold and wait until we have the urgent fixed merged.

**Comment by g4s8** [comment]
@paulodamaso yes, sorry, I tried to post this comment to this PR: https://github.com/artipie/rpm-adapter/pull/42

This one is not blocking by any other tickets.

**Comment by paulodamaso** [comment]
> @paulodamaso we also need to use this tag argument in docker build action: https://github.com/artipie/artipie/blob/master/.github/workflows/docker-release.yml

@g4s8 I think that we are already using the `tag_names` parameter, so the realeases are already being pushed by their git name

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#57` is not assigned, can't get performer

**Pull request merged**
