### PR TITLE
Add proof templates per each repo type

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #154.

### CODE REVIEW

**Comment by Sammers21** [comment]
@g4s8, review the pull request.

**Comment by Sammers21** [comment]
@g4s8, the badges will arrive in PR with examples. How does it sound to you?

**Comment by Sammers21** [comment]
@g4s8, the #331 contains all you need.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Pull request merged**
