### PR TITLE
Normalize Docker paths

### PR DESCRIPTION
**Pull request by g4s8**
#274 - Programmatically normalize Docker `/v2` requests to Artipie path format: `/v2/repo/image` -> `/repo/image`.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#293](https://github.com/artipie/artipie/issues/293) is assigned to @olegmoz[/z](https://www.0crat.com/u/olegmoz), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/8f22b121-da09-43a9-bed4-3474135b3099); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; @olegmoz[/z](https://www.0crat.com/u/olegmoz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@olegmoz I added real path from URI back before sending request to underlying slice, please check https://github.com/artipie/artipie/pull/293/commits/6c5a9545648d3c88e342bbaa264e5463d6382e7d

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olegmoz[/z](https://www.0crat.com/u/olegmoz), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by sereshqua** [comment]
@g4s8 i could not have tagged Oleg, so I did not wait for approval

**Pull request merged**
