### PR TITLE
Migrate to gem 0.4

### PR DESCRIPTION
**Pull request by Sammers21**
Migrate to gem-adapter version 0.4 and fix gem proof.

Related to #154.

### CODE REVIEW

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, merging

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@f6508573-5a3f-49c5-b3b6-e3aa5531dba6, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.in.orders.close_job
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.54.5](https://github.com/zerocracy/farm): CID: [6fd5cb16-89df-4f05-b6e2-ddb942d7245a](https://www.0crat.com/footprint/CT2E6TK9B/6fd5cb16-89df-4f05-b6e2-ddb942d7245a), Type: "Close job"

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#560` is not assigned, can't get performer

**Pull request merged**
