### PR TITLE
feat: http3 slice server

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #1314 

Added http3 server to serve slices and tests.

### CODE REVIEW

**Comment by ChGen** [comment]
@olenagerasimova , I see that you use jetty 11. x dependencies. Currently http3 issue I reported scheduled for version `12.0.2`, so I think its useful to start with jetty 12 release for http3.

**Comment by olenagerasimova** [comment]
@ChGen hm, I do not see versions 12.x in [maven-central](https://mvnrepository.com/artifact/org.eclipse.jetty.http3/http3-server)

**Comment by olenagerasimova** [comment]
@ChGen thanks, I've updated deps and code

**Comment by ChGen** [comment]
@olenagerasimova , in CI test runs I see an errors like `java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jetty.client.HttpClient`

**Comment by olenagerasimova** [comment]
@ChGen fixed (I've updated jetty http client in artipie http-client module)

**Review by ChGen — APPROVED** [review]
@olenagerasimova , LGTM.

**Review by dgarus — DISMISSED** [review]
Thanks!

**Comment by olenagerasimova** [comment]
@ChGen @dgarus 
I've added repository settings and start-up on http3 and corresponding documentation. 
I'd suggest not to merge this brunch yet:
Jetty **9** (witch was used in out http-client) and jetty **12** (the one with http3 implementation) are in conflicts, that's why I've updated jetty in http-client. And this jetty 12 appears to have [this NPE bug](https://github.com/jetty-project/jetty-reactive-httpclient/issues/296). That's why our integration tests with proxy are stuck. I hope jetty will fix the bug soon and we will be able to merge this branch.

Meanwhile, I'd suggest we discuss and perform some testing with maven-plugin and repository on http3. What do you say?

**Comment by ChGen** [comment]
@olenagerasimova , yes, I think we can continue in the http3 branch for the time being.

**Review by dgarus — APPROVED** [review]

**Pull request merged**
