### PR TITLE
#605 - npmInstall ITCase

### PR DESCRIPTION
**Pull request by genryxy**
Part of #605 
Add `npmInstall` for `NpmITCase`. Also updated npm-adapter from `0.7.5` to `0.7.6`

### CODE REVIEW

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy thanks, please see one minor comment

**Comment by genryxy** [comment]
@olegmoz thanks, corrected

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#710` is not assigned, can't get performer

**Pull request merged**
