### PR TITLE
Bump asto version

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #632.

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, merging

**Review by olegmoz — CHANGES_REQUESTED** [review]
@Sammers21 builds have failed after merging master branch, please look into this

**Comment by Sammers21** [comment]
@olegmoz, can we merge now?

**Review by olegmoz — APPROVED** [review]

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#631` is not assigned, can't get performer

**Pull request merged**
