### PR TITLE
#99 - Optional region & endpoint params in S3 storage config

### LINKED ISSUE #99: Some S3 storage settings should be optional
S3 storage configuration requires these settings:
```yaml
repo:
  type: file
  storage:
    type: s3
    region: eu-central-1
    url: s3://artipie.test/binary
    endpoint: https://s3.eu-central-1.amazonaws.com
    bucket: artipie.test
    credentials:
      type: basic
      accessKeyId: <id>
      secretAccessKey: <secret>
```
Default AWS CLI tool requires only access key and secret key (except bucket name), all other parameters should be optional. So this configuration can be working without additional parameters:
```yaml
```yaml
repo:
  type: file
  storage:
    type: s3
    bucket: artipie.test
    credentials:
      type: basic
      accessKeyId: <id>
      secretAccessKey: <secret>
```
```

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #99

### CODE REVIEW

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dc9a75c2-99a9-40a1-bc27-ddaf8f08c10c, thread: PQ-CT2E6TK9B
com.zerocracy.farm.reactive.StkRuntime[76] java.lang.IllegalStateException: org.codehaus.groovy.runtime.InvokerInvocationException in com.zerocracy.stk.pm.scope.wbs.add_job_to_wbs
org.codehaus.groovy.reflection.CachedMethod[105] org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.12](https://github.com/zerocracy/farm): CID: [ff9881ce-9314-4057-a8ec-c5ff6d25ffa8](https://www.0crat.com/footprint/CT2E6TK9B/ff9881ce-9314-4057-a8ec-c5ff6d25ffa8), Type: "Add job to WBS"

**Comment by olegmoz** [comment]
@g4s8 could you tell please what's wrong with subject? It has common format and looks to match linter regex

**Comment by g4s8** [comment]
@olegmoz it was broken by this commit: https://github.com/artipie/artipie/commit/8124395912ba37e37bae86d0e9f34c034acf6d33
I'll fix it now

**Comment by g4s8** [comment]
@olegmoz thanks

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#103` is not assigned, can't get performer

**Pull request merged**
