### PR TITLE
Using storage prefixes

### PR DESCRIPTION
**Pull request by g4s8**
#159 - updated asto to `0.20.2`, using repo names as storage prefixes.

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#160](https://github.com/artipie/artipie/issues/160) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/268d329f-fa4a-43e6-88fb-5950cb01719c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@g4s8 Please solve conflicts. After this, it's good to merge

**Comment by g4s8** [comment]
@paulodamaso the storage prefixes are tested in `artipie/asto` repository, I don't think we should repeat same tests in this repo, since this repo is not in charge of testing submodule

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#160` is not assigned, can't get performer

**Pull request merged**
