### PR TITLE
Refactored HTTP layer

### PR DESCRIPTION
**Pull request by g4s8**
#258 - refactored HTTP layer

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#270](https://github.com/artipie/artipie/issues/270) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1fd9b5db-0e97-4e85-b84c-a1852ff961f7); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@g4s8 can you boost this one, its really long pr

**Comment by g4s8** [comment]
@0crat boost 2x

**Comment by g4s8** [comment]
@Vatavuk sure, done

**Comment by 0crat** [comment]
> @0crat boost 2x ([here](https://github.com/artipie/artipie/issues/270#issuecomment-654861115))

@g4s8 Boost 2x was set for [#270](https://github.com/artipie/artipie/issues/270)

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Pull request merged**
