### PR TITLE
#224 - UI tweaks

### PR DESCRIPTION
**Pull request by yegor256**
See #224: I made some small improvements

### CODE REVIEW

**Comment by g4s8** [comment]
@yegor256 please resolve merge conflicts. Also, `{{user}}` won't work for `repo.hbs`, since it doesn't provide such template, see https://github.com/artipie/artipie/blob/master/src/main/java/com/artipie/dashboard/RepoPage.java#L114

**Comment by yegor256** [comment]
@g4s8 done

**Comment by 0crat** [comment]
This pull request [#225](https://github.com/artipie/artipie/issues/225) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/da56c926-031b-4cab-ab28-d54f0d81594b); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@g4s8 please remove this issue from the scope

**Comment by g4s8** [comment]
@0crat out

**Comment by 0crat** [comment]
Job was finished in 14 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Pull request merged**
