### PR TITLE
fix #740

### LINKED ISSUE #740: Fix missing VOLUME declaration
Dockerfile should have VOLUME declaration for persistent data storage and config file as it told in [best-practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#volume).

Please see my pull request #741 

P.S. I had to move config file from `/etc/artipie.yml` to `/etc/artipie/artipie.yml` because it's almost impossible to declare volume as a file and not as directory.

P.P.S. Related to #75

### PR DESCRIPTION
**Pull request by iaroslavscript**
Fix for issue #740

### CODE REVIEW

**Review by olegmoz — CHANGES_REQUESTED** [review]
@iaroslavscript thanks for the PR. The idea to add `VOLUME` for config folder is nice, but changing configuration file location from `/etc/artipie.yml` to `/etc/artipie/artipie.yml` does not feel right as it is going to break existing installations

**Comment by iaroslavscript** [comment]
Hi @olegmoz 
Thanks for pointing that I totally forgot about backward-compatibility requirements.
Now it's fixed and **artipie** is able to read configs from `/etc/artipie.yml` as well as `/etc/artipie/artipie.yml`.
Please see my second commit.

**Review by olegmoz — APPROVED** [review]
@iaroslavscript thanks, merging

**Comment by iaroslavscript** [comment]
Thanks!

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#741` is not assigned, can't get performer

**Pull request merged**
