### PR TITLE
Enable gem proof

### PR DESCRIPTION
**Pull request by Sammers21**
Related to #154.

### CODE REVIEW

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by Sammers21** [comment]
@olegmoz, can you review, please?

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#474` is not assigned, can't get performer

**Pull request merged**
