### PR TITLE
#601 - updated go-adapter

### LINKED ISSUE #601: Update go-adapter
Let's bump go-adapter version and add pass users and auth there.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Updated go-adapter to close #601

### CODE REVIEW

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by olegmoz** [comment]
@olenagerasimova go proof is failing, please look into this

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, looks good

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#613` is not assigned, can't get performer

**Pull request merged**
