### PR TITLE
Group repositories implementation

### PR DESCRIPTION
**Pull request by g4s8**
#233 - group repositories implementation

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#254](https://github.com/artipie/artipie/issues/254) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e8d82025-37a7-4a71-b242-17f292a05e94); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/254#issuecomment-652960441))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#254](https://github.com/artipie/artipie/issues/254), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#254` is not assigned, can't get performer

**Pull request merged**
