### PR TITLE
#730 - use ContentAs from asto

### LINKED ISSUE #730: Artipie API slices should not depend on Settings
Let's make Artipie API do not depend on `Settings` interface. These slices will be moved to a separate repository, and should not depend on artipie `Settings`. 
Note that interfaces `RepoPermissions` and `Users`, class `RepoPermissions.PermissionItem` will be moved to the new repo along with these slices.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #730 
I've updated asto, removed `ContentAs` and created `ContentAsJson` and `ContentAsYaml`

### CODE REVIEW

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova it seems that integration tests hang up, please check

**Comment by olenagerasimova** [comment]
@olegmoz you were right about resetting position in `Remaining`, I've reverted `ContentAs` and ITs are running fine, check [this](https://github.com/olenagerasimova/artipie/pull/1) PR in my fork. Now, I'd like to discuss further actions: maybe, we should do not reset `ByteBuffer` position in `PublisherAs`?

**Comment by olegmoz** [comment]
@olenagerasimova I guess we need to locate particular place in code that causes troubles when switched from `Concatenation` to `PublisherAs` and try to understand why it's happening. Or maybe keep this particular place in code with `Concatenation` & `Remaining` usage and add a `@todo` for migration

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks for figuring this out, merging

**Pull request merged**
