### PR TITLE
Push directly to central.artipie.com and dont fail on error

### LINKED ISSUE #656: Docker images build always fail
image
image

Fail reason: https://github.com/artipie/artipie/runs/1197839942?check_suite_focus=true#step:6:12

```
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

### PR DESCRIPTION
**Pull request by Sammers21**
Closes #656

### CODE REVIEW

**Comment by Sammers21** [comment]
@olegmoz, can you review the PR please?

**Comment by 0crat** [comment]
@Sammers21 this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Review by olegmoz — APPROVED** [review]
@Sammers21 thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#658` is not assigned, can't get performer

**Pull request merged**
