### PR TITLE
#231 - Added NopMetrics, NopCounter and NopGauge

### PR DESCRIPTION
**Pull request by olegmoz**
Part of #231 
Added `NopMetrics`, `NopCounter` and `NopGauge`.
Expected to be used as `Metrics` implementation when metrics collecting and publishing is disabled

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#262](https://github.com/artipie/artipie/issues/262) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/51fa6700-51a8-45ea-997f-193eb41c07b5); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by Vatavuk** [comment]
@sereshqua ping

**Comment by g4s8** [comment]
@0crat quality bad

**Pull request merged**
